kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-cm
  namespace: openshift-gitops
data:
  resource.customizations.health.operator.coreos.com_Subscription: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.installedCSV ~= nil then
        hs.status = "Healthy"
        hs.message = "CSV Installed"
        if obj.status.state ~= nil then
          hs.message = obj.status.state
        end
        return hs
      end
    end
    hs.status = "Progressing"
    hs.message = "Unknown"
    if obj.status.state ~= nil then
      hs.message = obj.status.state
    end
    return hs
  resource.customizations.health.operators.coreos.com_InstallPlan: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.phase ~= nil then
        hs.message = obj.status.phase
        if obj.status.phase == "Complete" then
          hs.status = "Healthy"
        else
          hs.status = "Progressing"
        end
        return hs
      end
    end
    hs.status = "Progressing"
    hs.message = "Unknown"
    return hs
  resource.customizations.ignoreDifferences.operators.coreos.com_OperatorGroup: |
    jsonPointers:
    - /metadata/annotations/olm.providedAPIs